version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - intranet
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    volumes:
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl/
      - ${NGINX_LOG_PATH}:/var/log/nginx/
    ports:
      - "80:80
      - "443:443"
    networks:
      - intranet
  php-fpm:
    build:
      context: ./
      dockerfile: php.dockerfile
    env_file: '.env'
    networks:
      - intranet
networks:
  intranet:
